/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 02 21:03:20 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import ar.edu.unrc.game2048.DeterministicPlacement;
import ar.edu.unrc.game2048.NonDeterministicPlacement;
import ar.edu.unrc.game2048.PlacementStrategy;
import ar.edu.unrc.game2048.Position;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try {
        board0.validatePosition(0, 1438);
        fail("Expecting exception: IndexOutOfBoundsException");

      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 1438) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try {
        board0.getCell(4, 4);
        fail("Expecting exception: IndexOutOfBoundsException");

      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = new Board();
      board0.validatePosition(0, 0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board();
      LinkedList<Cell> linkedList0 = new LinkedList<Cell>();
      board0.removeEmptyCells(linkedList0);
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      LinkedList<Cell> linkedList0 = new LinkedList<Cell>();
      boolean boolean0 = board0.moveUp();
      assertTrue(boolean0);

      Cell cell0 = board0.getCell(0, 0);
      linkedList0.add(cell0);
      assertEquals("2", cell0.toString());

      board0.removeEmptyCells(linkedList0);
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board();
      LinkedList<Cell> linkedList0 = new LinkedList<Cell>();
      board0.mergeAdjacentEqualsCells(linkedList0);
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(1, deterministicPlacement0);
      Set<Position> set0 = board0.getEmptyPositions();
      assertTrue(board0.repOk());
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try {
        board0.validatePosition((-3264), (-3264));
        fail("Expecting exception: IndexOutOfBoundsException");

      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-3264, -3264) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(3, deterministicPlacement0);
      // Undeclared exception!
      try {
        board0.removeEmptyCells((List<Cell>) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try {
        board0.padWithEmptyCells((List<Cell>) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board(54);
      // Undeclared exception!
      board0.moveRight();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try {
        board0.mergeAdjacentEqualsCells((List<Cell>) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      NonDeterministicPlacement nonDeterministicPlacement0 = new NonDeterministicPlacement();
      Board board0 = new Board(2339, nonDeterministicPlacement0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board(1705);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));

      board0.moveDown();
      boolean boolean0 = board0.equals(board1);
      assertFalse(board1.equals((Object)board0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board0.moveRight();
      boolean boolean0 = board0.equals(board1);
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      boolean boolean0 = board0.equals(board1);
      assertTrue(boolean0);
      assertEquals(4, board1.getSize());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals(board0);
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isLosingBoard();
      assertTrue(board0.repOk());
      assertFalse(boolean0);
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isWinningBoard();
      assertTrue(board0.repOk());
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(0, board0.getScore());
      assertTrue(boolean0);
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(1, deterministicPlacement0);
      boolean boolean0 = board0.hasEmptyCells();
      assertTrue(board0.repOk());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board();
      Set<Position> set0 = board0.getEmptyPositions();
      assertEquals(14, set0.size());
      assertTrue(board0.repOk());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(1, 0);
      board0.setCell(1, 0, cell0);
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(2, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getSize();
      assertEquals(4, int0);
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.repOk();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      String string0 = board0.toString();
      assertTrue(board0.repOk());
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board board0 = new Board();
      LinkedList<Cell> linkedList0 = new LinkedList<Cell>();
      boolean boolean0 = board0.equals(linkedList0);
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals((Object) null);
      assertFalse(boolean0);
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board(4);
      board0.moveRight();
      boolean boolean0 = board0.moveRight();
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      int int0 = board0.getScore();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      NonDeterministicPlacement nonDeterministicPlacement0 = new NonDeterministicPlacement();
      Board board0 = new Board(1, nonDeterministicPlacement0);
      boolean boolean0 = board0.moveRight();
      assertTrue(board0.repOk());
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      boolean boolean0 = board0.repOk();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(1, deterministicPlacement0);
      boolean boolean0 = board0.moveLeft();
      assertEquals(1, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(1, deterministicPlacement0);
      boolean boolean0 = board0.moveDown();
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOk());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(1, deterministicPlacement0);
      board0.moveUp();
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      LinkedList<Cell> linkedList0 = new LinkedList<Cell>();
      board0.padWithEmptyCells(linkedList0);
      board0.mergeAdjacentEqualsCells(linkedList0);
      assertEquals(4, linkedList0.size());
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      NonDeterministicPlacement nonDeterministicPlacement0 = new NonDeterministicPlacement();
      Board board0 = new Board(1, nonDeterministicPlacement0);
      boolean boolean0 = board0.isFull();
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      assertFalse(boolean0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOk());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(1, deterministicPlacement0);
      boolean boolean0 = board0.isLosingBoard();
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(4, deterministicPlacement0);
      boolean boolean0 = board0.moveUp();
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try {
        board0.setCell(0, 4, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");

      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try {
        board0.getCell(2, (-3182));
        fail("Expecting exception: IndexOutOfBoundsException");

      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, -3182) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board(4);
      // Undeclared exception!
      try {
        board0.getCell(552, 1548);
        fail("Expecting exception: IndexOutOfBoundsException");

      } catch(IndexOutOfBoundsException e) {
         //
         // Position (552, 1548) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try {
        board0.setCell(0, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");

      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: IllegalArgumentException");

      } catch(IllegalArgumentException e) {
         //
         // Board to copy cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Board board0 = new Board(2, (PlacementStrategy) null);
      boolean boolean0 = board0.moveLeft();
      assertFalse(boolean0);
      assertEquals(2, board0.getSize());
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0, (PlacementStrategy) null);
        fail("Expecting exception: IllegalArgumentException");

      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");

      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Board board0 = new Board();
      board0.getStrategy();
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getScore();
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(4, board0.getSize());

      board0.getCell(0, 3);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOk());
  }
}
