/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 02 21:06:31 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import ar.edu.unrc.game2048.Position;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class Position_ESTest extends Position_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Position position0 = new Position((-1325), (-3114));
      String string0 = position0.toString();
      assertEquals("(-1325, -3114)", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Position position0 = new Position((-1325), (-3114));
      position0.hashCode();
      assertEquals((-1325), position0.row);
      assertEquals((-3114), position0.col);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Position position0 = new Position(0, 0);
      Position position1 = new Position(0, (-3405));
      boolean boolean0 = position0.equals(position1);
      assertEquals(0, position1.row);
      assertFalse(boolean0);
      assertEquals((-3405), position1.col);
      assertFalse(position1.equals((Object)position0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Position position0 = new Position(1858, 1858);
      Position position1 = new Position(1334, 1858);
      boolean boolean0 = position0.equals(position1);
      assertEquals(1858, position1.col);
      assertFalse(position1.equals((Object)position0));
      assertFalse(boolean0);
      assertEquals(1334, position1.row);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Position position0 = new Position(982, 2655);
      Position position1 = new Position(982, 2655);
      boolean boolean0 = position0.equals(position1);
      assertEquals(982, position1.row);
      assertEquals(2655, position1.col);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Position position0 = new Position((-80), (-80));
      Position position1 = new Position((-80), 55);
      boolean boolean0 = position0.equals(position1);
      assertFalse(boolean0);
      assertEquals((-80), position1.row);
      assertFalse(position1.equals((Object)position0));
      assertEquals(55, position1.col);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Position position0 = new Position(3208, 3208);
      Object object0 = new Object();
      boolean boolean0 = position0.equals(object0);
      assertEquals(3208, position0.col);
      assertEquals(3208, position0.row);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Position position0 = new Position(3208, 3208);
      boolean boolean0 = position0.equals(position0);
      assertEquals(3208, position0.row);
      assertEquals(3208, position0.col);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Position position0 = new Position(0, 0);
      boolean boolean0 = position0.equals((Object) null);
      assertEquals(0, position0.col);
      assertEquals(0, position0.row);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Position position0 = new Position((-80), (-80));
      Position position1 = new Position(55, (-80));
      boolean boolean0 = position0.equals(position1);
      assertFalse(boolean0);
      assertEquals(55, position1.row);
      assertEquals((-80), position1.col);
      assertFalse(position1.equals((Object)position0));
  }
}
