/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 17 17:45:01 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.DeterministicPlacement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DeterministicPlacement_ESTest extends DeterministicPlacement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(3);
      boolean boolean0 = deterministicPlacement0.addTile(board0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      // Undeclared exception!
      try { 
        deterministicPlacement0.addTile((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.DeterministicPlacement", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DeterministicPlacement deterministicPlacement0 = new DeterministicPlacement();
      Board board0 = new Board(1, deterministicPlacement0);
      boolean boolean0 = deterministicPlacement0.addTile(board0);
      assertFalse(boolean0);
  }
}
