/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 17 17:46:32 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.NonDeterministicPlacement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NonDeterministicPlacement_ESTest extends NonDeterministicPlacement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Board board0 = new Board(66);
      NonDeterministicPlacement nonDeterministicPlacement0 = new NonDeterministicPlacement();
      // Undeclared exception!
      nonDeterministicPlacement0.addTile(board0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NonDeterministicPlacement nonDeterministicPlacement0 = new NonDeterministicPlacement();
      // Undeclared exception!
      try { 
        nonDeterministicPlacement0.addTile((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.NonDeterministicPlacement", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Random.setNextRandom(2147483645);
      NonDeterministicPlacement nonDeterministicPlacement0 = new NonDeterministicPlacement();
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        nonDeterministicPlacement0.addTile(board0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -9
         //
         verifyException("java.util.stream.ReferencePipeline", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NonDeterministicPlacement nonDeterministicPlacement0 = new NonDeterministicPlacement();
      Board board0 = new Board(1);
      boolean boolean0 = nonDeterministicPlacement0.addTile(board0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NonDeterministicPlacement nonDeterministicPlacement0 = new NonDeterministicPlacement();
      Board board0 = new Board();
      nonDeterministicPlacement0.addTile(board0);
      nonDeterministicPlacement0.addTile(board0);
      boolean boolean0 = nonDeterministicPlacement0.addTile(board0);
      assertTrue(boolean0);
  }
}
