/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 17 17:48:06 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import ar.edu.unrc.game2048.Position;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Position_ESTest extends Position_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Position position0 = new Position((-1), 334);
      String string0 = position0.toString();
      assertEquals("(-1, 334)", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Position position0 = new Position((-1), 334);
      position0.hashCode();
      assertEquals(334, position0.col);
      assertEquals((-1), position0.row);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Position position0 = new Position((-1), (-1));
      Position position1 = new Position((-1), (-1104));
      boolean boolean0 = position0.equals(position1);
      assertEquals((-1), position1.row);
      assertFalse(position1.equals((Object)position0));
      assertFalse(boolean0);
      assertEquals((-1104), position1.col);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Position position0 = new Position((-1), 334);
      Position position1 = new Position((-1), 334);
      boolean boolean0 = position0.equals(position1);
      assertTrue(boolean0);
      assertEquals((-1), position1.row);
      assertEquals(334, position1.col);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Position position0 = new Position(0, (-863));
      Position position1 = new Position((-298), (-863));
      boolean boolean0 = position0.equals(position1);
      assertFalse(boolean0);
      assertFalse(position1.equals((Object)position0));
      assertEquals((-863), position1.col);
      assertEquals((-298), position1.row);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Position position0 = new Position((-39), (-54));
      Position position1 = new Position((-39), (-39));
      boolean boolean0 = position0.equals(position1);
      assertEquals((-39), position1.row);
      assertFalse(boolean0);
      assertFalse(position1.equals((Object)position0));
      assertEquals((-39), position1.col);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Position position0 = new Position((-3979), (-3979));
      Position position1 = new Position(3366, (-3979));
      boolean boolean0 = position0.equals(position1);
      assertEquals(3366, position1.row);
      assertFalse(position1.equals((Object)position0));
      assertEquals((-3979), position1.col);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Position position0 = new Position((-3978), (-3978));
      boolean boolean0 = position0.equals(position0);
      assertEquals((-3978), position0.col);
      assertEquals((-3978), position0.row);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Position position0 = new Position((-3978), (-3978));
      boolean boolean0 = position0.equals("(-3978, -3978)");
      assertFalse(boolean0);
      assertEquals((-3978), position0.col);
      assertEquals((-3978), position0.row);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Position position0 = new Position((-39), (-54));
      boolean boolean0 = position0.equals((Object) null);
      assertEquals((-39), position0.row);
      assertFalse(boolean0);
      assertEquals((-54), position0.col);
  }
}
